MBTN_LEFT_DBL cycle fullscreen
SPACE cycle pause;show-text '${?pause==yes:Pause}${!pause==yes:Play}'
PLAY cycle pause;show-text '${?pause==yes:Pause}${!pause==yes:Play}'
PAUSE cycle pause;show-text '${?pause==yes:Pause}${!pause==yes:Play}'
LEFT seek -5
RIGHT seek 5
UP seek -3 exact
DOWN seek 3 exact
CTRL+LEFT seek -60
CTRL+RIGHT seek 60
PREV add chapter -1
NEXT add chapter 1
SHIFT+LEFT add sub-delay -0.1
SHIFT+RIGHT add sub-delay 0.1
ALT+LEFT add audio-delay -0.1
ALT+RIGHT add audio-delay 0.1
WHEEL_UP no-osd add volume 5;show-text 'Volume ${volume}%'
WHEEL_DOWN no-osd add volume -5;show-text 'Volume ${volume}%'
i script-binding stats/display-stats-toggle
ESC script-binding commands/open
I no-osd set hwdec vaapi;set vulkan-device 'Intel(R) Iris(R) Xe Graphics (RPL-P)'
N no-osd set hwdec nvdec;set vulkan-device 'NVIDIA GeForce RTX 4060 Laptop GPU'
#着色器
c no-osd set glsl-shaders '';show-text 'Clear'
a no-osd set glsl-shaders '~/.local/share/mpv/Anime4K_Restore_CNN_M.glsl:~/.local/share/mpv/Anime4K_Thin_Fast.glsl:~/.local/share/mpv/Anime4K_Upscale_CNN_x2_M.glsl:~/.local/share/mpv/Anime4K_AutoDownscalePre_x2.glsl:~/.local/share/mpv/Anime4K_Denoise_Bilateral_Mode.glsl:~/.local/share/mpv/AMD_CAS_rgb.glsl';show-text 'Anime4K'
#右键菜单
MBTN_RIGHT script-message-to context_menu open
