autocreate-playlist=same
directory-mode=ignore
hwdec-software-fallback=48
hwdec=nvdec
input-default-bindings=no
keep-open=yes
load-positioning=no
media-controls=no
msg-level=input=error
title=${path}
volume-max=100
vulkan-device='NVIDIA GeForce RTX 4060 Laptop GPU'

sub-border-size=1
sub-font-size=65
sub-margin-x=0
sub-margin-y=0

osd-align-x=right
osd-bar=no
osd-border-size=1
osd-duration=1500
osd-font-size=55
osd-on-seek=msg

script-opt=osc-boxalpha=255
script-opt=osc-deadzonesize=1
script-opt=osc-layout=slimbox
script-opt=osc-seekbarhandlesize=1.1
script-opt=osc-seekbarstyle=diamond
script-opt=osc-timetotal=yes
script-opt=osc-valign=1.04

script-opt=console-border_size=0.7
script-opt=console-font_size=16

script-opt=stats-border_size=0.7
script-opt=stats-key_exit=
script-opt=stats-key_page_0=KP0
script-opt=stats-key_page_1=KP1
script-opt=stats-key_page_2=KP2
script-opt=stats-key_page_3=KP3
script-opt=stats-key_page_4=KP4
script-opt=stats-key_page_5=KP5
