listener {
    timeout = 1500
    on-timeout = /usr/lib/systemd/systemd-backlight save backlight:intel_backlight; exec swayosd-client --brightness=-50
    on-resume = exec /usr/lib/systemd/systemd-backlight load backlight:intel_backlight
}

listener {
    timeout = 1800
    on-timeout = exec hyprctl dispatch "hl.dsp.dpms({ action = 'disable' })"
    on-resume = exec hyprctl dispatch "hl.dsp.dpms({ action = 'enable' })"
}

listener {
    timeout = 3600
    on-timeout = exec systemctl suspend
}
