listener {
    timeout = 1500
    on-timeout = exec brightnessctl -s set 10%
    on-resume = exec brightnessctl -r
}

listener {
    timeout = 1800
    on-timeout = exec hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = exec hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 3600
    on-timeout = exec systemctl suspend
}
